// This file is generated by generator.ts
public struct AssistantMessage: Codable, Hashable {
  public let customSessionId: String?
  public let fromText: Bool
  public let id: String?
  public let message: ChatMessage
  public let models: Inference
  public let type: String
}
