//
//  AssistantEnd.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation

public struct AssistantEnd: Decodable {
  let type: String

  public init() {
    self.type = "assistant_end"
  }
}
