// This file is generated by generator.ts
public struct AssistantProsody: Codable, Hashable {
  public let customSessionId: String?
  public let id: String?
  public let models: Inference
  public let type: String
}
