// This file is generated by generator.ts
public struct AssistantInput: Codable, Hashable {
  public let customSessionId: String?
  public let text: String
  public let type: String

  public init(customSessionId: String?, text: String) {
    self.customSessionId = customSessionId
    self.text = text
    self.type = "assistant_input"
  }
}
