// This file is generated by generator.ts
public struct AudioConfiguration: Codable, Hashable {
  public let channels: Int
  public let encoding: Encoding
  public let sampleRate: Int

  public init(channels: Int, encoding: Encoding, sampleRate: Int) {
    self.channels = channels
    self.encoding = encoding
    self.sampleRate = sampleRate
  }
}
