// This file is generated by generator.ts
public struct AudioOutput: Codable, Hashable {
  public let customSessionId: String?
  public let data: String
  public let id: String
  public let index: Int
  public let type: String
}
