// This file is generated by generator.ts
public struct AudioOutput: Codable {
  public let customSessionId: String?
  public let data: String
  public let id: String
  public let index: Int
  public let type: String

  public init(customSessionId: String?, data: String, id: String, index: Int, type: String) {
    self.customSessionId = customSessionId
    self.data = data
    self.id = id
    self.index = index
    self.type = type
  }
}
