// This file is generated by generator.ts
public struct ChatMessage: Codable, Hashable {
  public let content: String?
  public let role: Role
  public let toolCall: ToolCallMessage?
  public let toolResult: ChatMessageToolResult?
}
