// This file is generated by generator.ts
public struct ChatMetadata: Codable, Hashable {
  public let chatGroupId: String
  public let chatId: String
  public let customSessionId: String?
  public let requestId: String?
  public let type: String
}
