// This file is generated by generator.ts
public typealias EmotionScores = [String: Double]

extension EmotionScores {
  // Named accessors for emotion scores

  public var admiration: Double {
    return self["Admiration"] ?? 0.0
  }

  public var adoration: Double {
    return self["Adoration"] ?? 0.0
  }

  public var aestheticAppreciation: Double {
    return self["Aesthetic Appreciation"] ?? 0.0
  }

  public var amusement: Double {
    return self["Amusement"] ?? 0.0
  }

  public var anger: Double {
    return self["Anger"] ?? 0.0
  }

  public var anxiety: Double {
    return self["Anxiety"] ?? 0.0
  }

  public var awe: Double {
    return self["Awe"] ?? 0.0
  }

  public var awkwardness: Double {
    return self["Awkwardness"] ?? 0.0
  }

  public var boredom: Double {
    return self["Boredom"] ?? 0.0
  }

  public var calmness: Double {
    return self["Calmness"] ?? 0.0
  }

  public var concentration: Double {
    return self["Concentration"] ?? 0.0
  }

  public var confusion: Double {
    return self["Confusion"] ?? 0.0
  }

  public var contemplation: Double {
    return self["Contemplation"] ?? 0.0
  }

  public var contempt: Double {
    return self["Contempt"] ?? 0.0
  }

  public var contentment: Double {
    return self["Contentment"] ?? 0.0
  }

  public var craving: Double {
    return self["Craving"] ?? 0.0
  }

  public var desire: Double {
    return self["Desire"] ?? 0.0
  }

  public var determination: Double {
    return self["Determination"] ?? 0.0
  }

  public var disappointment: Double {
    return self["Disappointment"] ?? 0.0
  }

  public var disgust: Double {
    return self["Disgust"] ?? 0.0
  }

  public var distress: Double {
    return self["Distress"] ?? 0.0
  }

  public var doubt: Double {
    return self["Doubt"] ?? 0.0
  }

  public var ecstasy: Double {
    return self["Ecstasy"] ?? 0.0
  }

  public var embarrassment: Double {
    return self["Embarrassment"] ?? 0.0
  }

  public var empathicPain: Double {
    return self["Empathic Pain"] ?? 0.0
  }

  public var entrancement: Double {
    return self["Entrancement"] ?? 0.0
  }

  public var envy: Double {
    return self["Envy"] ?? 0.0
  }

  public var excitement: Double {
    return self["Excitement"] ?? 0.0
  }

  public var fear: Double {
    return self["Fear"] ?? 0.0
  }

  public var guilt: Double {
    return self["Guilt"] ?? 0.0
  }

  public var horror: Double {
    return self["Horror"] ?? 0.0
  }

  public var interest: Double {
    return self["Interest"] ?? 0.0
  }

  public var joy: Double {
    return self["Joy"] ?? 0.0
  }

  public var love: Double {
    return self["Love"] ?? 0.0
  }

  public var nostalgia: Double {
    return self["Nostalgia"] ?? 0.0
  }

  public var pain: Double {
    return self["Pain"] ?? 0.0
  }

  public var pride: Double {
    return self["Pride"] ?? 0.0
  }

  public var realization: Double {
    return self["Realization"] ?? 0.0
  }

  public var relief: Double {
    return self["Relief"] ?? 0.0
  }

  public var romance: Double {
    return self["Romance"] ?? 0.0
  }

  public var sadness: Double {
    return self["Sadness"] ?? 0.0
  }

  public var satisfaction: Double {
    return self["Satisfaction"] ?? 0.0
  }

  public var shame: Double {
    return self["Shame"] ?? 0.0
  }

  public var surpriseNegative: Double {
    return self["Surprise (negative)"] ?? 0.0
  }

  public var surprisePositive: Double {
    return self["Surprise (positive)"] ?? 0.0
  }

  public var sympathy: Double {
    return self["Sympathy"] ?? 0.0
  }

  public var tiredness: Double {
    return self["Tiredness"] ?? 0.0
  }

  public var triumph: Double {
    return self["Triumph"] ?? 0.0
  }
}
