// This file is generated by generator.ts

public typealias EmotionScores = [String: Double]

extension EmotionScores {

  public var admiration: Double { self["Admiration"] ?? 0.0 }

  public var adoration: Double { self["Adoration"] ?? 0.0 }

  public var aestheticAppreciation: Double { self["Aesthetic Appreciation"] ?? 0.0 }

  public var amusement: Double { self["Amusement"] ?? 0.0 }

  public var anger: Double { self["Anger"] ?? 0.0 }

  public var anxiety: Double { self["Anxiety"] ?? 0.0 }

  public var awe: Double { self["Awe"] ?? 0.0 }

  public var awkwardness: Double { self["Awkwardness"] ?? 0.0 }

  public var boredom: Double { self["Boredom"] ?? 0.0 }

  public var calmness: Double { self["Calmness"] ?? 0.0 }

  public var concentration: Double { self["Concentration"] ?? 0.0 }

  public var confusion: Double { self["Confusion"] ?? 0.0 }

  public var contemplation: Double { self["Contemplation"] ?? 0.0 }

  public var contempt: Double { self["Contempt"] ?? 0.0 }

  public var contentment: Double { self["Contentment"] ?? 0.0 }

  public var craving: Double { self["Craving"] ?? 0.0 }

  public var desire: Double { self["Desire"] ?? 0.0 }

  public var determination: Double { self["Determination"] ?? 0.0 }

  public var disappointment: Double { self["Disappointment"] ?? 0.0 }

  public var disgust: Double { self["Disgust"] ?? 0.0 }

  public var distress: Double { self["Distress"] ?? 0.0 }

  public var doubt: Double { self["Doubt"] ?? 0.0 }

  public var ecstasy: Double { self["Ecstasy"] ?? 0.0 }

  public var embarrassment: Double { self["Embarrassment"] ?? 0.0 }

  public var empathicPain: Double { self["Empathic Pain"] ?? 0.0 }

  public var entrancement: Double { self["Entrancement"] ?? 0.0 }

  public var envy: Double { self["Envy"] ?? 0.0 }

  public var excitement: Double { self["Excitement"] ?? 0.0 }

  public var fear: Double { self["Fear"] ?? 0.0 }

  public var guilt: Double { self["Guilt"] ?? 0.0 }

  public var horror: Double { self["Horror"] ?? 0.0 }

  public var interest: Double { self["Interest"] ?? 0.0 }

  public var joy: Double { self["Joy"] ?? 0.0 }

  public var love: Double { self["Love"] ?? 0.0 }

  public var nostalgia: Double { self["Nostalgia"] ?? 0.0 }

  public var pain: Double { self["Pain"] ?? 0.0 }

  public var pride: Double { self["Pride"] ?? 0.0 }

  public var realization: Double { self["Realization"] ?? 0.0 }

  public var relief: Double { self["Relief"] ?? 0.0 }

  public var romance: Double { self["Romance"] ?? 0.0 }

  public var sadness: Double { self["Sadness"] ?? 0.0 }

  public var satisfaction: Double { self["Satisfaction"] ?? 0.0 }

  public var shame: Double { self["Shame"] ?? 0.0 }

  public var surpriseNegative: Double { self["Surprise (negative)"] ?? 0.0 }

  public var surprisePositive: Double { self["Surprise (positive)"] ?? 0.0 }

  public var sympathy: Double { self["Sympathy"] ?? 0.0 }

  public var tiredness: Double { self["Tiredness"] ?? 0.0 }

  public var triumph: Double { self["Triumph"] ?? 0.0 }
}
