// This file is generated by generator.ts
public struct PauseAssistantMessage: Codable, Hashable {
  public let customSessionId: String?
  public let type: String

  public init(customSessionId: String?) {
    self.customSessionId = customSessionId
    self.type = "pause_assistant_message"
  }
}
