// This file is generated by generator.ts
public struct ResumeAssistantMessage: Codable, Hashable {
  public let customSessionId: String?
  public let type: String

  public init(customSessionId: String?) {
    self.customSessionId = customSessionId
    self.type = "resume_assistant_message"
  }
}
