// This file is generated by generator.ts

public enum Role: String, Codable {
  case assistant = "assistant"
  case system = "system"
  case user = "user"
  case all = "all"
  case tool = "tool"
  case context = "context"
}
