// This file is generated by generator.ts
public struct SessionSettings: Codable, Hashable {
  public let audio: AudioConfiguration?
  public let builtinTools: [BuiltinToolConfig]?
  public let context: Context?
  public let customSessionId: String?
  public let languageModelApiKey: String?
  public let systemPrompt: String?
  public let tools: [Tool]?
  public let type: String
  public let variables: [String: String]?

  public init(
    audio: AudioConfiguration?, builtinTools: [BuiltinToolConfig]?, context: Context?,
    customSessionId: String?, languageModelApiKey: String?, systemPrompt: String?, tools: [Tool]?,
    variables: [String: String]?
  ) {
    self.audio = audio
    self.builtinTools = builtinTools
    self.context = context
    self.customSessionId = customSessionId
    self.languageModelApiKey = languageModelApiKey
    self.systemPrompt = systemPrompt
    self.tools = tools
    self.variables = variables
    self.type = "session_settings"
  }
}
