// This file is generated by generator.ts
public struct ToolCallMessage: Codable, Hashable {
  public let customSessionId: String?
  public let name: String
  public let parameters: String
  public let responseRequired: Bool
  public let toolCallId: String
  public let toolType: ToolType?
  public let type: String
}
