//
//  ToolResponseMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct ToolResponseMessage: Codable {
    let type: String
    let toolCallId: String
    let content: String
    let customSessionId: String?

    public init(type: String,
                toolCallId: String,
                content: String,
                customSessionId: String?) {
        self.type = type
        self.toolCallId = toolCallId
        self.content = content
        self.customSessionId = customSessionId
    }
}
