// This file is generated by generator.ts
public struct ToolErrorMessage: Codable, Hashable {
  public let code: String?
  public let content: String?
  public let customSessionId: String?
  public let error: String
  public let level: ErrorLevel?
  public let toolCallId: String
  public let toolType: ToolType?
  public let type: String

  public init(
    code: String?, content: String?, customSessionId: String?, error: String, level: ErrorLevel?,
    toolCallId: String, toolType: ToolType?
  ) {
    self.code = code
    self.content = content
    self.customSessionId = customSessionId
    self.error = error
    self.level = level
    self.toolCallId = toolCallId
    self.toolType = toolType
    self.type = "tool_error"
  }
}
