//
//  ToolCallMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation

public struct ToolCallMessage: Codable {

    public let name: String
    public let parameters: String
    public let toolCallId: String
    public let toolType: ToolType
    public let responseRequired: Bool
    public let type: String?
    public let customSessionId: String?

    public init(name: String,
                parameters: String,
                toolCallId: String,
                toolType: ToolType,
                responseRequired: Bool,
                type: String?,
                customSessionId: String?) {
        self.name = name
        self.parameters = parameters
        self.toolCallId = toolCallId
        self.toolType = toolType
        self.responseRequired = responseRequired
        self.type = type
        self.customSessionId = customSessionId
    }
}
