// This file is generated by generator.ts
public struct Tool: Codable, Hashable {
  public let description: String?
  public let fallbackContent: String?
  public let name: String
  public let parameters: String
  public let type: ToolType

  public init(
    description: String?, fallbackContent: String?, name: String, parameters: String, type: ToolType
  ) {
    self.description = description
    self.fallbackContent = fallbackContent
    self.name = name
    self.parameters = parameters
    self.type = type
  }
}
