// This file is generated by generator.ts
public struct UserMessage: Codable, Hashable {
  public let customSessionId: String?
  public let fromText: Bool
  public let interim: Bool
  public let message: ChatMessage
  public let models: Inference
  public let time: MillisecondInterval
  public let type: String
}
