// This file is generated by generator.ts
public struct PostedUtteranceVoiceWithId: Codable, Hashable {
  public let id: String
  public let provider: VoiceSourceProvider

  /// - Parameters:
  ///    - id: The unique ID associated with the Voice.
  ///    - provider: Specifies the source provider associated with the chosen voice. If no provider is explicitly set, the default provider is `CUSTOM_VOICE`. When using voices from Hume’s **Voice Library**, you must explicitly set the provider to `HUME_AI`.
  public init(id: String, provider: VoiceSourceProvider) {
    self.id = id
    self.provider = provider
  }
}
