// This file is generated by generator.ts
public struct PostedUtteranceVoiceWithName: Codable, Hashable {
    public let name: String
    public let provider: VoiceSourceProvider
    
    /// - Parameters:
    ///  - name: The name of a Voice.
    ///    - provider: Specifies the source provider associated with the chosen voice. If no provider is explicitly set, the default provider is `CUSTOM_VOICE`. When using voices from Hume’s **Voice Library**, you must explicitly set the provider to `HUME_AI`.
    public init(name: String, provider: VoiceSourceProvider) {
        self.name = name
        self.provider = provider
    }
}
