//
//  AudioOutput.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct AudioOutput: Codable {
    public let customSessionId: String?
    /** Base64 encoded audio output. */
    public let data: String
    /** ID of the audio output. */
    public let id: String
    public let type: String
    
    
    /// Attempts to decode the base64 encoded `data` attributed into
    /// a `Data` type that can be played.
    public var base64ToData: Data? {
        get { Data(base64Encoded: data) }
    }
}
