//
//  ToolResponseMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct ToolResponseMessage: Codable {
    let type: String
    let toolCallId: String
    let content: String
    let customSessionId: String?
}
