//
//  ToolErrorMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation

public struct ToolErrorMessage: Codable {
    let type: String
    let toolCallId: String
    let content: String
    let error: String
    let customSessionId: String?
    let code: String?
    let level: String?
}
