//
//  ToolCallMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation

public struct ToolCallMessage: Codable {

    let name: String
    let parameters: String
    let toolCallId: String
    let toolType: ToolType
    let responseRequired: Bool
    let type: String?
    let customSessionId: String?
}
