//
//  UserInput.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


/**
 * User text to insert into the conversation.
 */
public struct UserInput: Codable {
    
    let customSessionId: String?
    /** User text to insert into the conversation. */
    let text: String
    let type: String
    
    init(customSessionId: String? = nil, text: String) {
        self.customSessionId = customSessionId
        self.text = text
        self.type = "user_input"
    }
    
    
}
