//
//  UserMessage.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct UserMessage: Codable {    
    public let fromText: Bool
    public let message: ChatMessage
    public let models: Inference
    public let customSessionId: String?
    public let time: MillisecondInterval
    public let type: String
    public let interim: Bool
}
