//
//  UserInterruption.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct UserInterruption: Codable {
    let customSessionId: String?
    let time: Int
    let type: String
}
