//
//  WebSocketError.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct WebSocketError: Codable {
    /** Error code. */
    public let code: String
    public let customSessionId: String?
    /** Error message. */
    public let message: String
    /** Error slug. */
    public let slug: String
    public let type: String

    public init(code: String,
                customSessionId: String?,
                message: String,
                slug: String,
                type: String) {
        self.code = code
        self.customSessionId = customSessionId
        self.message = message
        self.slug = slug
        self.type = type
    }
}

public enum WebSocketErrorType: String {
    case chatGroupNotFound = "E0708"
    case chatResumeFailed = "E0710"
    
    static func from(_ error: WebSocketError) -> WebSocketErrorType? {
        WebSocketErrorType(rawValue: error.code)
    }
    
    public var message: String {
        switch self {
        case .chatGroupNotFound: "Could not retrieve previous chat history. Please start a new chat"
        case .chatResumeFailed: "Could not resume previous chat. Please start a new chat"
        }
    }
}
