//
//  WebSocketError.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public struct WebSocketError: Codable {
    /** Error code. */
    public let code: String
    public let customSessionId: String?
    /** Error message. */
    public let message: String
    /** Error slug. */
    public let slug: String
    public let type: String
}
