// This file is generated by generator.ts

public enum Format: String, Codable {
  case mp3
  case pcm
  case wav

  private enum CodingKeys: String, CodingKey {
    case type
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let rawValue = try container.decode(String.self, forKey: .type)
    guard let format = Format(rawValue: rawValue) else {
      throw DecodingError.dataCorruptedError(
        forKey: .type,
        in: container,
        debugDescription: "Invalid TTSFormat type: \(rawValue)"
      )
    }
    self = format
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.rawValue, forKey: .type)
  }
}
