// This file is generated by generator.ts
public struct PostedContextWithUtterances: Codable, Hashable {
  public let utterances: [PostedUtterance]

  public init(utterances: [PostedUtterance]) {
    self.utterances = utterances
  }
}
