// This file is generated by generator.ts
public struct PostedUtterance: Codable, Hashable {
  public let description: String?
  public let speed: Double?
  public let text: String
  public let trailingSilence: Double?
    
    public init(
        description: String? = nil,
        speed: Double? = nil,
        text: String,
        trailingSilence: Double? = nil
    ) {
        self.description = description
        self.speed = speed
        self.text = text
        self.trailingSilence = trailingSilence
    }
}
