// This file is generated by generator.ts
public struct PostedUtteranceVoiceWithId: Codable, Hashable {
  public let id: String
  public let provider: TTSVoiceProvider?

  public init(
    id: String,
    provider: TTSVoiceProvider?
  ) {
    self.id = id
    self.provider = provider
  }
}
