// This file is generated by generator.ts
import Foundation

public enum PostedTtsContext: Codable, Hashable {
  case postedContextWithGenerationId(PostedContextWithGenerationId)
  case postedContextWithUtterances(PostedContextWithUtterances)

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let postedContextWithGenerationId = try? container.decode(PostedContextWithGenerationId.self)
    {
      self = .postedContextWithGenerationId(postedContextWithGenerationId)
    } else if let postedContextWithUtterances = try? container.decode(
      PostedContextWithUtterances.self)
    {
      self = .postedContextWithUtterances(postedContextWithUtterances)
    } else {
      throw DecodingError.typeMismatch(
        PostedTtsContext.self,
        DecodingError.Context(
          codingPath: decoder.codingPath,
          debugDescription: "Invalid value for PostedTtsContext"
        )
      )
    }
  }
}
