// This file is generated by generator.ts
public struct PostedContextWithGenerationId: Codable, Hashable {
  public let generationId: String

  public init(generationId: String) {
    self.generationId = generationId
  }
}
