// This file is generated by generator.ts
public struct PostedTts: Codable, Hashable {
  public let format: Format
  public let numGenerations: Int
  public let splitUtterances: Bool
  public let stripHeaders: Bool
  public let utterances: [PostedUtterance]
    
    public init(format: Format, numGenerations: Int, splitUtterances: Bool, stripHeaders: Bool, utterances: [PostedUtterance]) {
        self.format = format
        self.numGenerations = numGenerations
        self.splitUtterances = splitUtterances
        self.stripHeaders = stripHeaders
        self.utterances = utterances
    }
}
