// This file is generated by generator.ts
public struct ReturnGeneration: Codable, Hashable {
  public let audio: String
  public let duration: Double
  public let encoding: AudioEncoding
  public let fileSize: Int
  public let generationId: String
  public let snippets: [[Snippet]]
}
