// This file is generated by generator.ts
public struct Snippet: Codable, Hashable {
  public let audio: String
  public let generationId: String
  public let id: String
  public let text: String
  public let transcribedText: String?
  public let utteranceIndex: Int?
}
