// This file is generated by generator.ts

public enum VoiceSourceProvider: String, Codable {
  /// Select voices from Hume’s [Voice Library](https://platform.hume.ai/tts/voice-library), containing a variety of preset, shared voices.
  case humeAi = "HUME_AI"
  /// Select from voices you’ve personally generated and saved in your account.
  case customVoice = "CUSTOM_VOICE"
}
