// This file is generated by generator.ts

import Foundation

public class TTSClient {

  private let networkClient: NetworkClient

  init(networkClient: NetworkClient) {
    self.networkClient = networkClient
  }
  public lazy var tts: TTS = { TTS(networkClient: networkClient) }()
}
