//
//  UserInputTest.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import XCTest

@testable import Hume

final class UserInputTest: XCTestCase {

  let encoder = JSONEncoder()

  func test_encoding() throws {
    let value = UserInput(text: "Hello, Hume!")

    let data = try! encoder.encode(value)
    let json = try! JSONSerialization.jsonObject(with: data) as! [String: Any]

    XCTAssertEqual(json["text"] as? String, "Hello, Hume!")
    XCTAssertEqual(json["type"] as? String, "user_input")
  }
}
