//
//  File.swift
//
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public class Chats {
    
    public func listChats() async throws {
        fatalError("TODO: Not yet implemented")
    }
    
    public func listChatEvents() async throws {
        fatalError("TODO: Not yet implemented")
    }
}
