// This file is generated by generator.ts

import Foundation

public class EmpathicVoice {

  internal let options: HumeClient.Options

  init(options: HumeClient.Options) {
    self.options = options
  }

}
