//
//  File.swift
//  
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public class EmpathicVoice {
    
    private let options: HumeClient.Options

    init(options: HumeClient.Options) {
        self.options = options
    }
    
    public lazy var chat: Chat = { Chat(options: options) }()

}
